config/routes.rb
Metablast::Application.routes.draw do
  resources :carts

  devise_for :game_users
	
	resources :answers

  resources :collections do
		resources :questions
	end

  resources :questions
	
	namespace :groups do
		get 'find'
		post 'search'
	end
	
  resources :groups do
		get 'members'
		post 'remove_member'
		post 'make_admin'
		post 'remove_admin'
		get 'invite'
		post 'send_invite'
		post 'accept_invite'
		post 'reject_invite'
		post 'join'
		post 'leave'
		post 'accept_member'
		post 'reject_member'
		
		resources :collections
	end

	root :to => 'dashboard#home'
	
  
  namespace :api do
		post 'patch_notes'
		
    namespace :groups do
      post 'get_users'# Change to GET pending Mark's change
      post 'get_active_users'# Change to GET pending Mark's change
      post 'get_pending_users'# Change to GET pending Mark's change
      post 'get_by_user' # Change  to GET pending Mark's change
      post 'join'#
      post 'invite'#
      post 'accept_invite' #
      post 'reject_invite' #
      post 'accept_member' #
      post 'reject_member' #
      post 'create' #
      post 'remove' #
      post 'make_admin' 
      post 'remove_member'#
    end
    
    namespace :game_users do
      post 'login'#
      post 'logout'#
      post 'sign_up'#
      post 'get_groups' # Change to GET pending Mark's change
      get 'get_pending_groups'#
      get 'get_active_groups'#
      get 'get_questions'#
      get 'get_groups_by_user'
      get 'add_statistic'
    end
    
    namespace :statistics do
      post 'add'
    end
    
    namespace :questions do
      post 'get_data'# Change to GET pending Mark's change
      post 'submit_answer'#
      post 'submit'#
      post 'remove'
    end
    
    namespace :collections do
      post 'create'#
      post 'remove'#
      post 'edit'#
    end

  end
  
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :group
  has_many :questions
  
  validates_presence_of :description

  attr_accessible :id
  
      
  def self.create_collection(game_user, group, description)
    collection = Collection.create(:description => description, :creator_id => game_user.id)
    group.collections << collection
    collection
  end
  
  def self.edit_collection(group, description, collection_id)
    collection = Collection.find_by_id(collection_id)
    if collection.nil?
      Error.create(:error_type_id => '8', :name => 'Collection deletion failure.', :description => 'That collection does not exist.')
    else      
      collection.description = description
      collection.save
      collection
    end
  end
  
  def self.remove_collection(group, collection_id)
    collection = Collection.find_by_id(collection_id)
    if collection.nil?
      Error.create(:error_type_id => '8', :name => 'Collection deletion failure.', :description => 'That collection does not exist.')
    else
      collection.destroy
      collection
    end
  end

  def copy_collection_data(collection_id, group_id, creator_id)
    old_col = Collection.find_by_id(collection_id)
    new_col = Collection.new(old_col.attributes.merge(:collection_id => collection.id.last + 1,  :creator_id => creator_id, :group_id => group_id))
    new_col
  end
   
end

app/controllers/api/collections_controller.rb
class Api::CollectionsController < ApiController
	# See API Documentation on Basecamp
	
  before_filter :verify_token
  before_filter :verify_group
  before_filter :verify_collection_params, :only => [:create_collection]
  before_filter :verify_edit_params, :only => [:edit_collection]
  before_filter :verify_remove_params, :only => [:remove_collection]
  
  def create
    authorize! :create_collection, @group
    render :xml => Collection.create_collection(@game_user, @group, params[:description])
  end
  
  def remove
    authorize! :create_collection, @group
    render :xml => Collection.remove_collection(@group, params[:collection_id])
  end
  
  def edit
    authorize! :create_collection, @group
    render :xml => Collection.edit_collection(@group, params[:description], params[:collection_id])
  end
  
  private 
  
  def verify_edit_params
    unless params.has_key?(:token) && params.has_key?(:group_id) && params.has_key?(:collection_id) && params.has_key?(:description)
      error = Error.create(:error_type_id => '2', :name => 'Parameter failure.', :description => 'Incorrect number of parameters.  Please check them.')
      render :xml => error.to_xml(:only => [:error_type_id, :name, :description, :created_at])
    end
  end
  
  def verify_remove_params
    unless params.has_key?(:token) && params.has_key?(:group_id) && params.has_key?(:collection_id)
      error = Error.create(:error_type_id => '2', :name => 'Parameter failure.', :description => 'Incorrect number of parameters.  Please check them.')
      render :xml => error.to_xml(:only => [:error_type_id, :name, :description, :created_at])
    end
  end
  
  def verify_collection_params
    unless params.has_key?(:token) && params.has_key?(:group_id) && params.has_key?(:description)
      error = Error.create(:error_type_id => '2', :name => 'Parameter failure.', :description => 'Incorrect number of parameters.  Please check them.')
      render :xml => error.to_xml(:only => [:error_type_id, :name, :description, :created_at])
    end
  end
  
  def verify_token
    #Refactor
    
    @token = AuthToken.find_by_token(params[:token])
    if @token.nil? || !@token.deleted_at.nil?
      error = Error.create(:error_type_id => '3', :name => 'AuthToken Error', :description => 'That token was either expired or not found.')
      render :xml => error.to_xml(:only => [:error_type_id, :name, :description, :created_at])    
    else
      @game_user = @token.game_user
    end
    
  end
  
  def verify_group
    group = Group.find_by_id(params[:group_id])
    if group.blank?
      error = Error.create(:error_type_id => '4', :name => 'Group Error', :description => 'Invalid group.')
      render :xml => error.to_xml(:only => [:error_type_id, :name, :description, :created_at])   
    else
      @group = group
      @current_ability ||= GroupAbility.new(@game_user, @group)
    end
  end
  
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
	load_and_authorize_resource
	
	before_filter :get_group, :only => [:new, :create, :index]
	
	respond_to :html
	
  def index
		@collections = @collections.where(:group_id => params[:group_id])
  end

  def show

  end

  def new

  end

  def edit
	
  end

  def create
		@collection.creator_id = current_game_user.id
		@collection.group = @group
		
		if @collection.save
			flash[:notice] = 'Collection was successfully created.'
		end
		
		respond_with(@collection)
  end

  def update
		if @collection.update_attributes(params[:collection])
			flash[:notice] = 'Collection was successfully updated.'
		end
		
		respond_with(@collection)
  end

  def destroy	
		if @collection.destroy
			flash[:notice] = 'Collection was successfully removed.'
		end
		
		respond_with(@collection, :location => group_collections_path(@collection.group))
  end
	
	private
	
	def get_group
		@group = Group.find(params[:group_id])
		# Using this instead of a load_and_authorize_resource (LAAR) :collection, :through => :group
		# because it is broken in Rails 3.1
		authorize! :access, @group
	end
	
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.haml
= form_for([@group, @collection]) do |f|
  = render 'shared/error_messages', :errorable => @collection
  
  .fields
    .field
      = f.label :name
      = f.text_field :name
      <span title=" the 'Name' box is for the title of the module/question set">[?]</span>
    .field
      = f.label :description
      = f.text_area :description
      <span title=" the 'Description' box is for any information about the question set (for example 'Photosynthesis' could have the description 'Questions about the chloroplast') "">[?]</span>

  .submit_button
    = f.submit "Create module", :class => 'btn btn-primary'
  

app/views/collections/edit.html.haml
.row
  .well
    .page-header
      %h1 Editing Collection

    = render 'form'

    = link_to 'Back', group_collections_path(@collection.group)

app/views/collections/index.html.haml
= content_for :content_left do
  .row
    .well
      .page-header
        %h2 Modules for #{link_to(@group.name, groups_path)}
      
      %table.table.table-bordered.table-striped
        %thead
          %th
            Description
          %th
            Show
          %th
            Edit
          %th
            Delete
        - @collections.each do |collection|
          %tbody
            %td
              #{collection.description}
            %td= link_to 'Show', collection
            %td= link_to 'Edit', edit_collection_path(collection)
            %td= link_to 'Destroy', collection, :confirm => 'Are you sure?', :method => :delete
              
              
= content_for :content_right do
  .row
    .well
      %ul.nav.nav-list
        %li.nav-header
          Toolbar
        %li 
          = link_to new_group_collection_path(@group) do
            %i.icon-plus
            Add a Module

app/views/collections/new.html.haml
= content_for :content_left do
  .well
    .row
      .page-header
        %h2
          = display_bread_crumbs([@group, 'Add a New Module'])

    .content
      = render :partial => 'form'

app/views/collections/show.html.haml
= content_for :content_left do
  .row
    .well
      .page-header
        %h2= display_bread_crumbs([@collection.group, @collection])
        
      %table.table.table-bordered.table-striped
        %thead
          %tr 
            %th Number of Questions:
          %tbody
            %td.last
              #{@collection.questions.length}
          
  .row
    .well
      .page-header.dashboard-header
        %h2 Questions
      - if @collection.questions.empty?
        You have no questions yet, please create one from the link to the right.
      - else
        %table.table.table-bordered.table-striped
          %thead
            %tr 
              Content
          - @collection.questions.each do |question|
            %tr
              %td
                #{link_to question.content, question}

      
= content_for :content_right do      
  - if can? :access, @collection
    .row
      .well
        %ul.nav.nav-list
          %li.nav-header
            Admin Options          
          %li
            = link_to new_collection_question_path(@collection) do
              %i.icon-plus
              Add Question
          %li
            = link_to collection_path, :method => :delete, :confirm => 'Are you sure you want to remove this Module? THIS IS IRREVERSIBLE AND INCLUDES ALL QUESTIONS' do
              %i.icon-remove
              Remove
          %li
            = link_to groups_path do
              %i.icon-adjust
              Merge Module
  