config/routes.rb
Metablast::Application.routes.draw do
  resources :carts

  devise_for :game_users
	
	resources :answers

  resources :collections do
		resources :questions
	end

  resources :questions
	
	namespace :groups do
		get 'find'
		post 'search'
	end
	
  resources :groups do
		get 'members'
		post 'remove_member'
		post 'make_admin'
		post 'remove_admin'
		get 'invite'
		post 'send_invite'
		post 'accept_invite'
		post 'reject_invite'
		post 'join'
		post 'leave'
		post 'accept_member'
		post 'reject_member'
		
		resources :collections
	end

	root :to => 'dashboard#home'
	
  
  namespace :api do
		post 'patch_notes'
		
    namespace :groups do
      post 'get_users'# Change to GET pending Mark's change
      post 'get_active_users'# Change to GET pending Mark's change
      post 'get_pending_users'# Change to GET pending Mark's change
      post 'get_by_user' # Change  to GET pending Mark's change
      post 'join'#
      post 'invite'#
      post 'accept_invite' #
      post 'reject_invite' #
      post 'accept_member' #
      post 'reject_member' #
      post 'create' #
      post 'remove' #
      post 'make_admin' 
      post 'remove_member'#
    end
    
    namespace :game_users do
      post 'login'#
      post 'logout'#
      post 'sign_up'#
      post 'get_groups' # Change to GET pending Mark's change
      get 'get_pending_groups'#
      get 'get_active_groups'#
      get 'get_questions'#
      get 'get_groups_by_user'
      get 'add_statistic'
    end
    
    namespace :statistics do
      post 'add'
    end
    
    namespace :questions do
      post 'get_data'# Change to GET pending Mark's change
      post 'submit_answer'#
      post 'submit'#
      post 'remove'
    end
    
    namespace :collections do
      post 'create'#
      post 'remove'#
      post 'edit'#
    end

  end
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	def home
		@pending_invites = GameUserGroup.where(:game_user_id => current_game_user.id, :state => 'invite_pending')
	end
	
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/home.html.haml
= content_for :content_left do
  .row
    .well
      .page-header.dashboard-header
        %h2 My Meta!Blast Account Snapshot
        
      %table.table.table-bordered.table-striped
        %thead
          %tr
            %th Member of:    
            %th Pending invitations:
        %tbody
          %tr
            %td
              #{current_game_user.groups.length} Groups
            %td.last
              #{@pending_invites.length}
  .row         
    .well
      .page-header.dashboard-header
        %h2 My Groups
        
      %table.table.table-bordered.table-striped
        %thead
          %tr
            %th
              Name:
            %th
              Number of Members:
          %tbody
            - current_game_user.groups.each do |group|
              %tr
                %td
                  - if current_game_user.admin_in_group?(group)
                    #{link_to group.name, group}*
                  - elsif cannot? :read, group
                    #{group.name} - Pending Admin Approval
                  - else
                    #{link_to group.name, group}
                    
                %td
                  #{group.game_users.length}
                
  .row
    .well
      .page-header.dashboard-header
        %h2 Popular Groups
        
      %table.table.table-bordered.table-striped
        %thead
          %tr
            %th
              Name:
            %th
              Number of Members:
            %th
              Join:
        %tbody
          - Group.limit(10).each do |group|
            %tr
              %td
                - if current_game_user.admin_in_group?(group)
                  #{link_to group.name, group}*
                - else
                  #{link_to group.name, group}
              %td
                #{group.game_users.length}
              %td
                = link_to group_join_path(group), :method => :post do
                  %i.icon-plus-sign
              
  .row
    .well
      .page-header.dashboard-header
        %h2 My Invitations
      - if @pending_invites.length > 0 
        %table.table.table-bordered.table-striped
          %tbody
            %tr
              %th
                Group Name
              %th
                Accept
              %th
                Reject
          %thead
            - @pending_invites.each do |invite|
              %tr
                %td
                  = invite.group.name
                %td
                  = link_to 'Accept', group_accept_invite_path(invite.group, :game_user_group_id => invite.id), :method => :post
                %td
                  = link_to 'Reject', group_reject_invite_path(invite.group, :game_user_group_id => invite.id), :method => :post
      - else
        You currently have no pending invites, hooray!


  
= content_for :content_right do
  .row
    .well
      %ul.nav.nav-list
        %li.nav-header
          Toolbar
        %li
          = link_to new_group_path do
            %i.icon-plus
            Add a Group 
        %li
          = link_to groups_find_path do
            %i.icon-comment
            Find a Group
        %li
          = link_to groups_path do 
            %i.icon-edit
            Edit Groups 
            /don't like how this works should #refactor - brian   