config/routes.rb
Metablast::Application.routes.draw do
  resources :carts

  devise_for :game_users
	
	resources :answers

  resources :collections do
		resources :questions
	end

  resources :questions
	
	namespace :groups do
		get 'find'
		post 'search'
	end
	
  resources :groups do
		get 'members'
		post 'remove_member'
		post 'make_admin'
		post 'remove_admin'
		get 'invite'
		post 'send_invite'
		post 'accept_invite'
		post 'reject_invite'
		post 'join'
		post 'leave'
		post 'accept_member'
		post 'reject_member'
		
		resources :collections
	end

	root :to => 'dashboard#home'
	
  
  namespace :api do
		post 'patch_notes'
		
    namespace :groups do
      post 'get_users'# Change to GET pending Mark's change
      post 'get_active_users'# Change to GET pending Mark's change
      post 'get_pending_users'# Change to GET pending Mark's change
      post 'get_by_user' # Change  to GET pending Mark's change
      post 'join'#
      post 'invite'#
      post 'accept_invite' #
      post 'reject_invite' #
      post 'accept_member' #
      post 'reject_member' #
      post 'create' #
      post 'remove' #
      post 'make_admin' 
      post 'remove_member'#
    end
    
    namespace :game_users do
      post 'login'#
      post 'logout'#
      post 'sign_up'#
      post 'get_groups' # Change to GET pending Mark's change
      get 'get_pending_groups'#
      get 'get_active_groups'#
      get 'get_questions'#
      get 'get_groups_by_user'
      get 'add_statistic'
    end
    
    namespace :statistics do
      post 'add'
    end
    
    namespace :questions do
      post 'get_data'# Change to GET pending Mark's change
      post 'submit_answer'#
      post 'submit'#
      post 'remove'
    end
    
    namespace :collections do
      post 'create'#
      post 'remove'#
      post 'edit'#
    end

  end
  
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :game_user_groups, :dependent => :destroy
  has_many :game_users, :through => :game_user_groups
  has_many :collections
	belongs_to :owner, :class_name => 'GameUser'
  
  validates_presence_of :name
  validates_uniqueness_of :name
	
	attr_protected :deleted_at
  
  def self.get_users(group)
    role_proc = Proc.new {|options, record| options[:builder].tag!('game-role-id', record.game_user_groups.where(:group_id => group.id).first.game_role.id)}
    game_user_proc = Proc.new {|options, record| options[:builder].tag!('id', record.id)}
    state_proc = Proc.new {|options, record| options[:builder].tag!('state', record.game_user_groups.where(:group_id => group.id).first.state)}
    group.game_users.to_xml(:procs => [role_proc, state_proc, game_user_proc])
  end
  
  def self.get_active_users(group)
    role_proc = Proc.new {|options, record| options[:builder].tag!('game-role-id', record.game_user_groups.where(:group_id => group.id).first.game_role.id)}
    game_user_proc = Proc.new {|options, record| options[:builder].tag!('id', record.id)}
    group.game_user_groups.where(:state => 'accepted').map(&:game_user).to_xml(:procs => [role_proc, game_user_proc])
  end
  
  def self.get_pending_users(group)
    role_proc = Proc.new {|options, record| options[:builder].tag!('game-role-id', record.game_user_groups.where(:group_id => group.id).first.game_role.id)}
    game_user_proc = Proc.new {|options, record| options[:builder].tag!('id', record.id)}
    state_proc = Proc.new {|options, record| options[:builder].tag!('state', record.game_user_groups.where(:group_id => group.id).first.state)}
    pending = group.game_user_groups.where(:state => 'pending_approval')
    invites = group.game_user_groups.where(:state => 'invite_pending')
    all_users = pending + invites
    all_users.map(&:game_user).to_xml(:procs => [role_proc, game_user_proc, state_proc])
  end  
  
  def self.join(game_user, group)
    role = GameRole.find_by_name('Member')
    gug = GameUserGroup.create(:game_user_id => game_user.id, :game_role_id => role.id, :group_id => group.id)
    gug.join_group
    gug
  end
  
  def self.invite(username, game_user_id, group)
    invited_user = GameUser.find_by_username(username);
    game_user = GameUser.find_by_id(game_user_id)
    role = GameRole.find_by_name('Member')
    gug = GameUserGroup.create(:game_user_id => invited_user.id, :inviter_id => game_user.id, :game_role_id => role.id, :group_id => group.id)
    gug.invite_to_group
    gug
  end

  def self.get_by_user(username)
    game_user = GameUser.find_by_username(username)
    game_user.groups
  end
  
  def self.accept_invite(gug)
    gug.accept_invite
    gug
  end
  
  def self.reject_invite(gug)
    gug.reject_invite
    gug
  end
  
  def self.accept_member(gug)
    gug.accept_member
    gug
  end
  
  def self.reject_member(gug)
    gug.reject_member
    gug
  end
  
  def self.remove_member(gug)
    gug.remove_member
    gug
  end
  
  def self.make_admin(gug)
    role = GameRole.find_by_name('Admin')
    gug.game_role_id = role.id
    if gug.save
      gug
    else
      error = Error.create(:error_type_id => '4', :name => 'Admin Creation Creation Failure', :description => gug.errors)
      error.to_xml(:only => [:error_type_id, :name, :description, :created_at])
    end
  end
  
  def self.create_group(game_user, params)
    group = Group.new(params[:group])
    group.owner_id = game_user.id
    if group.save
      role = GameRole.find_by_name('Owner')
      gug = GameUserGroup.create(:game_user_id => game_user.id, :game_role_id => role.id, :group_id => group.id, :state => 'accepted')
      gug.created_group
      group
    else
      error = Error.create(:error_type_id => '4', :name => 'Group Creation Failure', :description => group.errors)
      error.to_xml(:only => [:error_type_id, :name, :description, :created_at])
    end
  end
	
	def self.find_by_email(email)
		game_user = GameUser.find_by_email(email)
		if game_user.nil?
			return []
		else
			game_user.get_admin_groups + game_user.get_owner_groups
		end
	end
  
end

app/controllers/api/groups_controller.rb
class Api::GroupsController < ApiController
  before_filter :verify_groups_params, :except => [:create, :get_by_user]
  before_filter :verify_token
  before_filter :verify_group, :except => [:create, :get_by_user]
  
  def get_users
    authorize! :update, @group
    render :xml => Group.get_users(@group)
  end
  
  def get_pending_users
    authorize! :update, @group
    render :xml => Group.get_pending_users(@group)
  end
  
  def get_active_users
    authorize! :update, @group
    render :xml => Group.get_active_users(@group)
  end
  
  def join
    authorize! :join, @group
    render :xml => Group.join(@game_user, @group)
  end

  def get_by_user
    render :xml => Group.get_by_user(params[:username])
  end
  
  def invite
    authorize! :invite_to, @group
    render :xml => Group.invite(params[:username], params[:game_user_id], @group)
  end
  
  def accept_invite
    gug = GameUserGroup.where(:game_user_id => @game_user.id, :group_id => @group.id).first
    authorize! :accept_invite, gug
    render :xml => Group.accept_invite(gug)
  end
  
  def reject_invite
    gug = GameUserGroup.where(:game_user_id => @game_user.id, :group_id => @group.id).first
    authorize! :accept_invite, gug
    render :xml => Group.reject_invite(gug)
  end
  
  def accept_member
    game_user = GameUser.find(params[:accept_game_user_id])
    gug = GameUserGroup.where(:game_user_id => game_user.id, :group_id => @group.id).first
    authorize! :accept_member, gug
    render :xml => Group.accept_member(gug)
  end
  
  def reject_member
    game_user = GameUser.find(params[:reject_game_user_id])
    gug = GameUserGroup.where(:game_user_id => game_user.id, :group_id => @group.id).first
    authorize! :accept_member, gug
    render :xml => Group.reject_member(gug)
  end
  
  def remove_member
    game_user = GameUser.find(params[:joined_user_id])
    gug = GameUserGroup.where(:game_user_id => game_user.id, :group_id => @group.id).first
    authorize! :accept_member, gug
    render :xml => Group.remove_member(gug)
  end
  
  def make_admin
    game_user = GameUser.find(params[:joined_user_id])
    gug = GameUserGroup.where(:game_user_id => game_user.id, :group_id => @group.id).first
    authorize! :accept_member, gug
    render :xml => Group.make_admin(gug)
  end
  
  def create
    render :xml => Group.create_group(@game_user, params)
  end
  
  def remove
    authorize! :destroy, @group
    render :xml => @group.destroy
  end
  
  private
  
  
  def verify_groups_params
    unless params.has_key?(:token) && params.has_key?(:group_id)
      error = Error.create(:error_type_id => '2', :name => 'Parameter failure.', :description => 'Incorrect number of parameters.  Please check them.')
      render :xml => error.to_xml(:only => [:error_type_id, :name, :description, :created_at])
    end
  end
  
  def verify_token
    #Refactor
    @token = AuthToken.find_by_token(params[:token])
    if @token.nil? || !@token.deleted_at.nil?
      error = Error.create(:error_type_id => '3', :name => 'AuthToken Error', :description => 'That token was either expired or not found.')
      render :xml => error.to_xml(:only => [:error_type_id, :name, :description, :created_at])    
    else
      @game_user = @token.game_user
    end
  end
  
  def verify_group
    group = Group.find_by_id(params[:group_id])
    if group.blank?
      error = Error.create(:error_type_id => '4', :name => 'Group Error', :description => 'Invalid group.')
      render :xml => error.to_xml(:only => [:error_type_id, :name, :description, :created_at])   
    else
      @group = group
      @current_ability ||= GroupAbility.new(@game_user, @group)
    end
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	# All of the 'RESTful' actions will use this LAAR to handle the authorization.
	# The rest of the non RESTful sorts will use an authorize! line.
	load_and_authorize_resource
	
	respond_to :html
	
  def index

  end
	
  def show
		@pending_joins = @group.game_user_groups.where(:state => 'pending_approval')
  end

  def new

  end

  def edit
	
  end

  def create
		@group.owner = current_game_user
		
		if @group.save
			flash[:notice] = 'Group was successfully created.' 
			current_game_user.game_user_groups << GameUserGroup.create(:game_role_id => GameRole.find_by_name('Owner').id, :group_id => @group.id)
		end
		
		respond_with(@group)
  end
	
  def update
		flash[:notice] = 'Group was successfully updated.' if @group.update_attributes(params[:group])
		respond_with(@group)
  end

  def destroy
		flash[:notice] = 'Group was succesfully removed.' if @group.destroy
		respond_with(@group, :location => root_path)
  end
	
	def members
		# Set LAAR since this is non RESTFUL
		@group = Group.find(params[:group_id])
		authorize! :access, @group
		@members = @group.game_users
	end
	
	def remove_member
		group = Group.find(params[:group_id])
		game_user = GameUser.find(params[:game_user_id])
		gug = GameUserGroup.where(:game_user_id => game_user.id, :group_id => group.id).first
		authorize! :access, group
		
		if gug.destroy
			flash[:notice] = 'User successfully removed.'
			redirect_to group
		end
		
	end
	
	def invite
		@group = Group.find(params[:group_id])
	end
	
	def send_invite
		group = Group.find(params[:group_id])
		game_user = GameUser.find_by_email(params[:email])
		pending_role = GameRole.find_by_name('Pending')
		
		authorize! :access, group
		
		has_pending_invite = GameUser.check_pending_invites(game_user, group)
		
		case has_pending_invite
		
			when true
				flash[:error] = 'That user is already invited to that group or a user with that e-mail does not exist.'
				
			when false
				flash[:notice] = 'User has been successfully invited to the group.'
				game_user.invite_to_group(group)
				
		end # END case invited
		
		respond_with(group, :location => group_members_path(group))
	
	end
	
	def make_admin
		group = Group.find(params[:group_id])
		game_user = GameUser.find(params[:game_user_id])
		
		#TODO: REFACTOR OUT TO GAMEUSER METHOD (SAME WITH REMOVE)
		@gug = GameUserGroup.where(:game_user_id => game_user.id, :group_id => group.id).first
		admin_role = GameRole.find_by_name('Admin')
		authorize! :access, group
		
		@gug.game_role_id = admin_role.id
		
		if @gug.save
			flash[:notice] = "#{game_user.email} was succesfully added as an admin."
		end
		
		respond_with(@gug, :location => group_members_path(group))
	end
	
	def remove_admin
		group = Group.find(params[:group_id])
		game_user = GameUser.find(params[:game_user_id])
		admin_role = GameRole.find_by_name('Admin')
		member_role = GameRole.find_by_name('Member')
		@gug = GameUserGroup.where(:game_user_id => game_user.id, :group_id => group.id, :game_role_id => admin_role.id).first
		authorize! :access, group
		
		@gug.game_role_id = member_role.id
		
		if @gug.save
			flash[:notice] = "#{game_user.email} was succesfully removed as an admin."
		end
		
		respond_with(@gug, :location => group_members_path(group))
	end
	
	def accept_invite
		@gug = GameUserGroup.find(params[:game_user_group_id])
		authorize! :access, @gug
		
		if @gug.accept_invite
			flash[:notice] = 'You have successfully joined that group!'
		end
		
		respond_with(@gug, :location => group_path(@gug.group))
	end
	
	def reject_invite
		@gug = GameUserGroup.find(params[:game_user_group_id])
		authorize! :access, @gug
		
		if @gug.reject_invite
			flash[:notice] = 'You have successfully declined to join that group!'
			@gug.destroy
		end
		
		respond_with(@gug, :location => root_path)
	end
	
	def accept_member
		@gug = GameUserGroup.find(params[:game_user_group_id])
		authorize! :access, @gug.group
		
		if @gug.accept_member
			flash[:notice] = 'You have successfully accepted that member!'
		end
		
		respond_with(@gug, :location => group_path(@gug.group))
	end
	
	def reject_member
		@gug = GameUserGroup.find(params[:game_user_group_id])
		authorize! :access, @gug.group
		
		if @gug.reject_member
			flash[:notice] = 'You have successfully rejected that member!'
			@gug.destroy
		end
		
		respond_with(@gug, :location => group_path(@gug.group))
	end
	
	def find
	
	
	end
	
	def search
		@groups = Group.find_by_email(params[:email])
	end
	
	def join
		group = Group.find(params[:group_id])
		gug = Group.join(current_game_user, group)
		if gug.instance_of?(GameUserGroup) && gug.errors.empty?
			flash[:notice] = 'Join request succesfully sent to that group.  An admin must confirm your membership.'
		else
			flash[:error] = 'Join request failed.  Are you already a member of that group?'
		end
		respond_with(group, :location => root_path)
	end
	
	def leave
	
	end
	
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  = render 'shared/error_messages', :errorable => @group
  
  .fields
    .field
      = f.label :name
      = f.text_field :name
  
  .submit_button
    = f.submit "Create Group", :class => 'btn btn-primary'

app/views/groups/edit.html.haml
= content_for :content_left do
	.well
		.page-header
			%h2 Edit Group
			
		.content		
			= render :partial => 'form'

app/views/groups/find.html.haml
= content_for :content_left do
  .well
    .row
      .page-header
        %h2 Find a Group
    .content
      = form_tag(groups_search_path) do
        .fields
          .field
            = label_tag :email, 'E-mail of Admin/Owner'
            = email_field_tag :email
            
        .submit_button
          = submit_tag 'Search for Group', :class => 'btn btn-primary'

app/views/groups/index.html.haml
= content_for :content_left do
  .row
    .well
      .page-header
        %h2 Groups
      
      %table.table.table-bordered.table-striped
        %thead
          %th
            Name
          %th
            Modules
          %th
            Members
          %th
            Show
          %th
            Edit
          %th
            Delete
        - current_game_user.groups.each do |group|
          %thead
            %td
              #{group.name}
            %td
              = link_to "View", group_collections_path(group)
            %td
              = link_to "View", group_members_path(group)
            %td
              = link_to 'Show', group
            %td
              = link_to 'Edit', edit_group_path(group)
            %td
              = link_to 'Delete', group_path(group), :method => :delete, :confirm => 'Are you sure you want to remove this group?'
              
= content_for :content_right do
  .row
    .well
      %ul.nav.nav-list
        %li.nav-header
          Toolbar
        %li 
          = link_to new_group_path do 
            %i.icon-plus
            Add a group

app/views/groups/invite.html.haml
= content_for :content_left do
  .well
    .row
      .page-header
        %h2= display_bread_crumbs([@group, 'Invite a User'])
				
    = form_tag(group_send_invite_path(@group)) do
      .fields
        .field
          = label_tag :email
          = email_field_tag :email
            
      .submit_button
        = submit_tag "Invite", :class => 'btn btn-primary'

app/views/groups/members.html.haml
= content_for :content_left do
  .well
    .row
      .page-header
        %h2= display_bread_crumbs([@group, 'Members'])
      
    %table.table.table-bordered.table-striped
      %thead
        %tr 
          %th Email
          %th Remove
          %th Make Admin
          %th Remove Admin
      - @members.each do |member|
        %tbody
          %td #{member.email}
          %td= link_to image_tag('delete.png'), group_remove_member_path(:game_user_id => member.id), :method => :post, :confirm => 'Are you sure you want to remove this user?'
          %td= link_to 'Make Admin', group_make_admin_path(:game_user_id => member.id), :method => :post
          %td= link_to 'Remove Admin', group_remove_admin_path(:game_user_id => member.id), :method => :post
 
= content_for :content_right do
  .row
    .well
      %ul.nav.nav-list
        %li.nav-header
          General Options
        %li  
          = link_to group_invite_path(@group) do
            %i.icon-user
            Invite User

app/views/groups/new.html.haml
= content_for :content_left do
  .well
    .row
      .page-header
        %h2 Add a New Group
				
    = render :partial => 'form', :class => 'btn btn-primary'

app/views/groups/search.html.haml
= content_for :content_left do            
  .row
    .well
      .page-header
        %h2 Search Results:
      
      - if @groups.empty?
        .content
          No results for that search criteria, sorry.
      - else
        %table.table.table-bordered.table-striped
          %thead
            %tr
              %th
                Name
              %th
                Number of Members
              %th
                Join
          - @groups.each do |group|
            %tbody
              %td
                - if current_game_user.admin_in_group?(group)
                  #{link_to group.name, group}*
                - else
                  #{link_to group.name, group}
              %td
                #{group.game_users.length}
              %td
                = link_to group_join_path(group), :method => :post do
                  %i.icon-plus-sign

app/views/groups/show.html.haml
= content_for :content_left do
  .row
    .well
      .page-header.dashboard-header
        %h2= @group.name
      %table.table.table-bordered.table-striped
        %thead
          %tr
            %th Number of Members:
            %th Owner:
        %tbody
          %tr
            %td
              #{@group.game_users.length}
            %td.last
              #{@group.owner.email}
          
        
  .row
    .well
      .page-header.dashboard-header
        %h2 Modules

      - if @group.collections.empty?
        You have no modules yet, please create one from the link to the right.
      - else
        %table.table.table-bordered.table-striped
          %thead
            %tr
              %th
                Name
              %th
                Description
              %th
                Number of Questions:
          - @group.collections.each do |collection|
            %tbody
              %td
                #{link_to collection.name, collection}
              %td
                #{collection.description}
              %td
                #{collection.questions.length}

  - if can? :access, @group
    .row
      .well
        .page-header.dashboard-header
          %h2 Join Requests
        - if @pending_joins.empty?
          No join requests at this time.
        - else
          %table.table.table-bordered.table-striped
            %thead
              %tr
                %th
                  Email
                %th
                  Accept
                %th
                  Reject
            - @pending_joins.each do |pj|
              %tbody
                %tr
                  %td
                    = pj.game_user.email
                  %td
                    = link_to image_tag('add.png'), group_accept_member_path(pj.group, :game_user_group_id => pj.id), :method => :post
                  %td
                    = link_to image_tag('delete.png'), group_reject_member_path(pj.group, :game_user_group_id => pj.id), :method => :post
  
          
= content_for :content_right do
  .row
    .well
      %ul.nav.nav-list
        %li.nav-header
          General options
        %li
          = link_to group_members_path(@group) do
            %i.icon-th-list
            View Members
      
  - if can? :access, @group
    .row
      .well
        %ul.nav.nav-list
          %li.nav-header
            Admin options
          %li
            = link_to new_group_collection_path(@group) do
              %i.icon-plus
              Add a Module
          %li
            = link_to group_invite_path(@group) do
              %i.icon-user
              Invite User
          %li
            = link_to groups_path do 
              %i.icon-edit
              Edit Groups
          %li
            = link_to group_path(@group), :method => :delete, :confirm => 'Are you sure you want to remove this group? THIS IS IRREVERSIBLE' do
              %i.icon-remove
              Remove group