config/routes.rb
Metablast::Application.routes.draw do
  resources :carts

  devise_for :game_users
	
	resources :answers

  resources :collections do
		resources :questions
	end

  resources :questions
	
	namespace :groups do
		get 'find'
		post 'search'
	end
	
  resources :groups do
		get 'members'
		post 'remove_member'
		post 'make_admin'
		post 'remove_admin'
		get 'invite'
		post 'send_invite'
		post 'accept_invite'
		post 'reject_invite'
		post 'join'
		post 'leave'
		post 'accept_member'
		post 'reject_member'
		
		resources :collections
	end

	root :to => 'dashboard#home'
	
  
  namespace :api do
		post 'patch_notes'
		
    namespace :groups do
      post 'get_users'# Change to GET pending Mark's change
      post 'get_active_users'# Change to GET pending Mark's change
      post 'get_pending_users'# Change to GET pending Mark's change
      post 'get_by_user' # Change  to GET pending Mark's change
      post 'join'#
      post 'invite'#
      post 'accept_invite' #
      post 'reject_invite' #
      post 'accept_member' #
      post 'reject_member' #
      post 'create' #
      post 'remove' #
      post 'make_admin' 
      post 'remove_member'#
    end
    
    namespace :game_users do
      post 'login'#
      post 'logout'#
      post 'sign_up'#
      post 'get_groups' # Change to GET pending Mark's change
      get 'get_pending_groups'#
      get 'get_active_groups'#
      get 'get_questions'#
      get 'get_groups_by_user'
      get 'add_statistic'
    end
    
    namespace :statistics do
      post 'add'
    end
    
    namespace :questions do
      post 'get_data'# Change to GET pending Mark's change
      post 'submit_answer'#
      post 'submit'#
      post 'remove'
    end
    
    namespace :collections do
      post 'create'#
      post 'remove'#
      post 'edit'#
    end

  end
  
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  has_many :game_user_answers
  has_many :game_users, :through => :game_user_answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # GET /answers
  # GET /answers.xml
  def index
    @answers = Answer.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.xml
  def show
    @answer = Answer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.xml
  def new
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.xml
  def create
    @answer = Answer.new(params[:answer])

    respond_to do |format|
      if @answer.save
        format.html { redirect_to(@answer, :notice => 'Answer was successfully created.') }
        format.xml  { render :xml => @answer, :status => :created, :location => @answer }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @answer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.xml
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to(@answer, :notice => 'Answer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @answer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.xml
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to(answers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question_id %><br />
    <%= f.text_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :correct %><br />
    <%= f.check_box :correct %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <tr>
    <th>Question</th>
    <th>Correct</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @answers.each do |answer| %>
  <tr>
    <td><%= answer.question_id %></td>
    <td><%= answer.correct %></td>
    <td><%= answer.content %></td>
    <td><%= link_to 'Show', answer %></td>
    <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
    <td><%= link_to 'Destroy', answer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question:</b>
  <%= @answer.question_id %>
</p>

<p>
  <b>Correct:</b>
  <%= @answer.correct %>
</p>

<p>
  <b>Content:</b>
  <%= @answer.content %>
</p>


<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>